[build]
command = 'hugo'
context = 'production'
publish = 'public'

[build.environment]
HUGO_VERSION = '0.100.2'

[context.production]
[context.production.environment]
HUGO_VERSION = '0.100.2'
HUGO_ENV = 'production'
