---
title: Tools Toward Sublimity
author: J. Hagedorn
date: '2018-04-02'
slug: tools-toward-sublimity
categories: []
tags: []
---

Looking at the way that the *Self*, *Nature* and the *Sublime* are framed in Romantic-era science, it is intriguing to see how (even in fields supposedly untinged by subjectivity), the medium conveys and marinades the message.  It is difficult to imagine any scientist today, for instance, voicing the lines from William Herschel:^[See  [Darwin, G. H. (1912). Sir William Herschel. Science.](https://archive.org/stream/jstor-1637819/1637819#page/n9/mode/2up/search/luxuriant+garden)]

> This method of viewing the heavens seems to throw them into a new kind of light. They are now seen to resemble a luxuriant garden, which contains the greatest variety of productions in different flourishing beds... we can, as it were, extend the range of our experience to an immense duration

The converse is also true, and some media are inimical to conveying certain types of messages or subjects.  For instance, `syllogisms <> mysticism`, or `koans <> empirical experiments`, or `tweets <> dramatic monologues`.  This is not to say that one couldn't rastle these subjects into these forms; but the result would smack more of the incongruity, or the *pomo* dilution of meaning itself.

I can't help but think (or hope) that much of the subsequent erasure of the *Sublime* from scientific discourse following the Romantic period was due to a greater mechanization of method rather than any failure to experimentally verify the *Sublime*.^[Or perhaps not a mechanization of method, but a myopic focus on method as though it were the thing itself, with no built in longing for the mystery it referenced.]

In some ways, the humility woven into the scientific method itself might be said to have a kind of sublime ratio of *self::other* at its base.  The scientific method carries an implicit admission of the sublime baked into it, so that all theories and hypotheses are not considered 'true' but instead 'not yet disapproved'. A kind of *via negativa*, through which we know only by approaching, by almost knowing. This recalls the myth of Tantalus, where the fruit of the tree recedes as soon as he grasps it. Or perhaps more aptly that of Apollo and Daphne, in which she turns into a laurel tree as soon as Apollo (god of rationality and logic) approaches.

So what kind of tool enables one to approach the sublime? I want the answer to be something simple, like a pen, descendant of the feathery quill. Because one can only approach that which is infinitely weighty if one is unencumbered. Yet in the case of Humboldt and Herschel, this appears to be far from the case.

Humboldt drags large cases of scientific instruments up mountains, and the native people of Peru joke with him about the cyanometer which he uses to measure the blue of the sky. Herschel constructs gigantic lenses for his observatory in the countryside outside of London, where he spent long nights polishing them with a kind of mad focus on the medium of understanding.  It is clear that the tool itself is far from weightless.  And Herschel comes to his notion of the universe as a garden after years and years and years of patient observation. The tool becomes slight only with use.  Which is to say that one becomes dexterous in using the tool, yet there is a rub: one begins to have trouble differentiating ones own way of seeing from the way of seeing in which the tool promotes.  

Perhaps all tools can be tools toward sublimity, provided that they are seeing in the service of something greater and that their personal nature is acknowledged even though the whole can only be dimly sketched.  

And one other thing: in my experience sublimity can only be approached through this intensive use of tools. In poetry, for instance, through pattern and repetition.  It is easy to invoke the muse, but harder to construct a song.    Without attention to the medium, the broader aggregate claims are untrustworthy. The vatic utterances are just ideology.

This happens when we become impatient, when we begin to confuse our tools with the thing that they seek. So we get p-hacking in studies, and an aversion to publishing null results, when it is the finding that is valued and not the search.  One might note a similar cheapening of the sublime in the narrative and valuing of conversion experiences in contemporary evangelical Christians. Where conversion and assent to a dogmatic party line is valued at the expense of walking naked into the infinite. I tend to agree with Chesterton about heretics, not the truth is relative where that these heretics were correct, but that at least initially they saw truth as something which needed to be discovered and therefore which lay outside of themselves.

I only ever trusted the only opening sentences of Whitman’s song once I had read the lists and tallies.

Celebrating the triumph of orthodoxy, the survival of icons as tools, or the triumph of science against so I’m not mystery, are both opportunities for hubris.  They must always be seen as tentative, pair tension played out in each individual life.

Think of John Donne at the end of his life: “I tune my instrument here at the door, and what I must do their think here before. “. Where a tool or instrument is a rehearsal for some unimaginable way of seeing up at some higher frequency.  He did not succumb to listening to his own instrument as though it were the world beyond.  Just as her parents church windows both allow and block a few beyond, so with our tools.

All tools are infernal machines, which is to say but they are machines to escape her self-centeredness and to mediate the world. Yet we fall in love with the machines themselves and fall back down as in prelest, or delusion.  For example, Giordano Bruno’s ars memoria which was a kind of combination lock to break out of the self.  

Today we are all trapped in with the ancients would have called hell, between the isolation of ourselves in and see the outside world which we here is only partial and mediated, Not merely because of the fallibility of our senses but because it is mediated in its essence, whatever that may be by now.

I want what is the creator then all tools, all emotions medications, all rights and rituals, all images all maths, All interpretation, formulation, words and music. What holds these in its I like a dust mote.  And yet I know that I am perhaps only a tool, only son device which may catch the feeding reflection of a corner.  

Our tools must show their seams and wires, must carry the coal they use for electricity. Without guile, with all artifice they concoct and none other.
