---
title: Knowledge as a Medicinal Garden
author: J. Hagedorn
date: '2019-10-12'
slug: dataome
categories: []
---

Maybe my interest derives from a life saturated by the Christian notion of the *Word made flesh*.  Perhaps from an urge to reconcile my thoughts with the ungovernable sea of stuff surrounding me.  Or from any of the weaving-needles which continuously clack at the base of my cerebellum.  I'm not sure.  Nevertheless, I'm drawn to depictions of words which inhabit an uneasy space between symbolic and raw material.

The notion of the word as virus in Burroughs,^[see Burroughs, W.S. [Electronic Revolution](http://www.ubu.com/historical/burroughs/electronic_revolution.pdf), 1970.] compelled me when I first read it, as have the various myths in which words manifest themselves upon plants, and more recently the work in the field of biosemiotics: each of these strikes a chord in me which I  savor, yet fear is ridiculous.

In the paragraphs which follow, I won't be advancing any new theory, at least not deliberately: just hacking a path through some tangible words and hopefully learning how to live under their canopy. 

## Contexts of Knowledge: Internal and External

There are various ways of describing the 'stuff' of symbolized thoughts, but we can prompt a distinction to start: Is it inside of me or outside?

- **External:** What is housed outside of my body, but close-at-hand. Information as a *garden*, a *placenta*, a *library*.
- **Internal:** What has been ingested by me and materially changed me.  Information as *medicine*, a *virus*, *food*.

These are not mutually exclusive; in fact, they exist alongside each other every day.  I take information from the internet (*external*), think about it (*internal*), and write something on the internet in response (*external*). Neither of these distinctions is 'good' or 'bad'; a medicine (*pharmakon*) can be both healing agent and poison, and both possibilities are alive in it at any moment.  Words are pulsing with this power: we access it, take it into ourselves, and generate more. 

## External: The Placental Garden Library

What we collectively generate remains with us.  Created artifacts have their own life, independent of the biological existence of their makers. "Life is short, art is long", goes Horace's famous epigram.  But contrasting art with life doesn't do justice to their inter-penetration: the ways in which art insinuates itself into life, which in turn pollinates other art, and so on.  Shakespeare’s 18th sonnet gets closer to articulating this symbiosis, with its closing promise that "long lives this [*the poem*], and this gives life to thee."  Anything that *lives*, whether literally or figuratively, requires organization and maintenance, requires energy.

A recent essay on "*the selfish Dataome*" by astrophysicist Caleb Scharf^[See Scharf, C. [The Selfish Dataome](http://nautil.us/issue/65/in-plain-sight/the-selfish-dataome). *Nautilus*, Issue 065: In Plain Sight.] argues that the human race might usefully be conceived of as a supporting organelle for its own *dataome*: a portmanteau he defines as "the data outside of our biological selves."  Human knowledge exists like a placenta alongside the generations and civilizations: feeding us, entangled with us, yet somehow separate.

According to Scharf, this dataome encompasses all human representation of thoughts, and thus goes all the way back to handprints on cavern walls and myths in the oral tradition. It also broadens the notion of 'word' to include any artifact which represents a thought: that is, any data which is the representational exhaust of human perception and thought.  The cave paintings at Lascaux.  Photos of cat antics.  Wisdom literature.  The news.  The fake news.

This cloud of symbols and information is not precisely human, but floats alongside humanity like a placenta: a source of nourishment digesting the broader world and reconstituting it for us.  And just as the placenta was not invented or consciously constructed by humans, the act of patterning and representation exemplified by the *dataome* was not invented by us either.^[This seems contrary to Scharf's conception of the *dataome*, but borne out by considerations of symbolic activity that are less anthropocentric.  According to Jewish, Christian, Islamic, and other logocentric conceptions of reality, meaning is also 'unmade by hands': discovered not invented.  These conceptions are not solely held by religions, either.  See, for instance: Barbieri, Marcello. (2012). Codepoiesis – the Deep Logic of Life. Biosemiotics. 5. 10.1007/s12304-012-9162-4.  Or Umberto Eco's lovely reminiscence of a colleague in: Eco, Umberto. (2018). Giorgio Prodi and the lower threshold of semiotics. Sign Systems Studies. 46. 343. 10.12697/SSS.2018.46.2-3.07.]

Alongside these natural organisms, we humans, so adept at mimicry, create smaller external repositories.  Our derivative works are simpler, less faceted, with a practical beauty: the library, the garden.  Just as a library collects many books and organizes them, the garden collects many plants that may not naturally occur together.  I walk out to my garden to get some basil leaves; I go to the library to get books on systemic racism in America.

Let's lay out the relation between these external sources of nourishment in the form of analogies.  In each pair below, the first is natural and the second is a human-curated invention which mirrors it (i.e. *natural* : *mirror*)

*forest* : *garden* :: *placenta* : *meal* :: *dataome* : *library*

These are objects that we can point to, and they are also redolent with myth.  There are echoes of these images among various world-founding myths which frame creation as a separation of chaos from cosmos, such as the story of the Garden of Eden.  In this account, the first habitation of humans is not made by them but fashioned with love and care by Another: an Ur-garden similar to a placenta or womb.^[The symbolism of the altar of an Orthodox church as both Eden and womb, with the Theotokos as the sky, is a powerful merging of these symbols.]  The initial act is one of ordering, or creating a place where things are nourished and protected.  All of our making of gardens, whether the palatial or backyard variety, is an image of this ordering.  Similarly, the coagulation of strains of thoughts in books, and the sorting of those books in libraries, is an apprenticeship to the ongoing creation of meaning by Reality.

## Internal: Eating Living Medicine

Information enters into us and changes us, shaping our actions and our bodies: what we decide to ingest or tattoo on ourselves, where we live, who we consider 'safe' or 'dangerous'.  Information is not inert, not a pale pharmaceutical product.  It is closer to the 'plant allies' which we keep in our gardens and which constitute our food and medicine: living things we rely on in an interactive partnership.  The poet Samuel Taylor Coleridge advises: "accustom yourself to reflect on the words you use, hear, or read, their birth, derivation and history.  For if words are not THINGS, they are LIVING POWERS, by which the things of most importance to mankind are actuated, combined, and humanized."^[*Aids to Reflection*, p. 70.] 

While other analogies could certainly be found, Coleridge's description reminds me most of the cooking process: attention to the source of food, combination of ingredients, heating to aid digestion.  And words and other knowledge have been food to me... how many times have I felt empty and been nourished by a line of poetry?  Nourished and given a new mind, as food becomes and replaces our bodies with new matter.

In eastern traditions of Christian monasticism, monks would come to an elder (*geronda*) asking for 'a word' as though it were a prescription.  A controlled substance, for that matter: taken with care and fear of misuse.^[One famous story from the *Sayings of the Desert Fathers* relates that "A monk once came to Basil of Caesarea and said, 'Speak a word, Father'; and Basil replied, 'Thou shalt love the Lord thy God with all thy heart'; and the monk went away at once. Twenty years later he came back, and said, 'Father, I have struggled to keep your word; now speak another word to me'; and he said, 'Thou shalt love thy neighbor as thyself'; and the monk returned in obedience to his cell to keep that also."]  Anyone who has taken psychotropic medications knows their power to make one feel like a different person, whether for good or ill, and the mere existence of FDA safety testing points to the trust needed for us to accept such a power into our bodies.  Abuses of this trust are rightly vilified, exemplified by Big Tobacco or the Lilly Suicides ^[In which the company went to market with Prozac despite knowing the unacceptable risk of suicide caused by the drug.  For a medico-legal analysis, [see here](http://breggin.com/wp-content/uploads/1996/01/Website%20Introduction%20to%20documents.pdf).].  Equivalent abuses of trust using words and data by companies such as Facebook are actively harming broad swathes of humanity.^[See, for instance, evidence published in the *Wall Street Journal* that Facebook executives were aware that the site's algorithms "exploit the human brain's attraction to divisiveness" and that “if left unchecked” those algorithms would feed users "more and more divisive content in an effort to gain user attention".]  This parallel potential of thoughts, medicines, and food to do harm points to an underlying similarity: the intimate relationship of these materials to our selves and bodies when we ingest them.

Both food and medicine are metabolized by our bodies and become, in turn, part of the body's fabric. They are objects of our actions: we find them, prepare them, take them in.  Information can come to us in this way as well, but we often come by it far less intentionally.  We float in an ether of information and it enters us almost without our choosing.  So jingles get stuck in your head, and you know which brand a font belongs to, and your movement through virtual and physical worlds yields 'marketing impressions.'  Information and thoughts come to us unbidden, and often change us far more than we "make use" of them.  In this sense, knowledge is more like a bacteria, or virus.^[William Burroughs' aforementioned essay in *Electronic Revolution*, for instance, claims that the word has evolved to operate as a virus with the human as its host organism, and presciently identifies its dangers when militarized and used for control.]  It enters into our bodies and can be beneficial and harmful to us, but has a life of its own: or rather, [many lives](https://scholar.google.com/scholar?q=gut+microbiota+systematic+review).  If we do not take care in selecting what we eat, we are likely to lose hold of who we are.

