---
title: Parts of speech patterns
author: J. Hagedorn
date: '2019-01-26'
slug: parts-of-speech-patterns
tags:
  - prosody
meta_img: /images/image.jpg
---

```{r libs, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse); library(gutenbergr); library(cleanNLP); library(DT)
cnlp_init_udpipe()
```



```{r}
corpus <- feather::read_feather("../../static/data/corpus.feather")
```

```{r}

milton <-
  corpus %>%
  filter(title == "Paradise Lost") %>%
  select(text) %>%
  slice(1:75) %>%
  cnlp_annotate(.$text, as_strings = TRUE)

keats <-
  corpus %>%
  filter(author == "Keats, John") %>%
  select(text) %>%
  slice(c(5:18,38:289,297:365,375:546)) %>%
  cnlp_annotate(.$text, as_strings = TRUE)

```

```{r}

library(sunburstR)

cnlp_get_token(keats) %>%
  mutate(sentence = cumsum(str_detect(word, regex("^\\.$")))) %>%
  filter(word != ".") %>%
  group_by(sentence) %>%
  summarize(path = paste(tolower(upos), collapse = "-")) %>%
  group_by(path) %>%
  summarize(score = n()) %>%
  arrange(score) %>% 
  sunburst(
    # colors = list(
    #   range=cols,
    #   domain=legend_items
    # )
  )

```

```{r}
cols <- 
  c(
    colorRampPalette(RColorBrewer::brewer.pal(9, 'Blues'))(length(personal_items)),
    colorRampPalette(RColorBrewer::brewer.pal(9, 'Oranges'))(length(interpersonal_items)),
    colorRampPalette(RColorBrewer::brewer.pal(9, 'Greens'))(length(environment_items))
  )

sunburst_df %>%
  ungroup() %>%
  select(path,score) %>%
  arrange(score) %>% 
  sunburst(
    colors = list(
      range=cols,
      domain=legend_items
    )
  )
```

