---
title: Toward Good
author: J. Hagedorn
date: '2024-01-03'
description: ''
bibliography: spiral.bib
csl: "https://www.zotero.org/styles/chicago-fullnote-bibliography"
suppress-bibliography: yes
slug: []
---

I stand at the threshold.  I peer out from the doorway connecting my small, inner world with the clamorous beauty of Reality: and it makes me *want*.  Seeing the vasts of the world accentuates the gaps within me, filling me with that feeling we have come to call, strangely, *longing*.  "Longing, we say, because desire is full / of endless distances", as Robert Hass tells it.^[In his vulnerable [Meditation at Lagunitas](https://www.poetryfoundation.org/poems/47553/meditation-at-lagunitas), which ends with the mantra "*blackberry, blackberry, blackberry*"]

This desire coaxes me to change... something... about myself, my situation.  I know that tiny changes are possible each conscious moment, every time I move through the cycle of sensing, choosing and acting on the world. If I want to be purposeful in shaping this cycle, it certainly helps to have a clear understanding of myself, the patterns of behavior we call traits.  Yet I'm still left with a larger question: What do I want my patterns to change *into*?  Or, put another way: What is at the other end of my longing?


## An inventory of longing

At this point I could jump into my own litany of desires (some wholesome, some not so), but that wouldn't be particularly helpful. Or maybe just assume we all know what's good for us, and should just eat our proverbial broccoli, but that approach glosses over too many of the differences between our views of the world.

Rather than start by considering a small set of pre-defined 'virtues' and harboring a suspicion that something is being hidden from us by a morality we don’t share, let's begin by pulling together the broadest set of things that people want, without initially labeling them as either 'good' or 'bad'.^["'*Damn*' braces, '*Bless*' relaxes", advises William Blake.]

A helpful ally in this search for an *inventory of longing* is the research of Shalom Schwartz, whose theory of values provides common terms for a full range of human interests.^[These can include both charitable and selfish ends: because the list is descriptive and not prescriptive, it includes items that have historically been known as 'virtues' and 'vices'.] What I've been calling a desire, or a longing, Schwartz calls a value.  His theory and associated measurement tools^[These include various versions of the *Portrait Value Questionnaire*, including the brief version used the European Social Survey.  See: @schwartzRepositorySchwartzValue2021] have been used across various subsequent psychological studies, which allow us to consider values within discussions about personality traits, group cooperation, and other relevant areas.

__Values are broad goals that guide our lives.__ According to Schwartz,^[@schwartzMeasuringRefinedTheory2022] values are "trans-situational goals, varying in importance, that serve as guiding principles in the life of a person or other social entity."  Individual people can have values, but so can communities, organizations, or other groups. 

Below is the full list of values defined in this model, with simpler terms in the first column which I intend to use throughout the subsequent discussion:^[The shorter name concocted by me is followed by the longer one provided by Schwartz, and the definition drawn directly from [@schwartzMeasuringRefinedTheory2022]]

| Value          | SVS Term                   | Definition         | 
|----------------|----------------------------|--------------------|
| Dependability  | Benevolence-Dependability  | Being a reliable and trustworthy member of the in-group | 
| Caring         | Benevolence-Caring         | Devotion to the welfare of in-group members |
| Non-Judgment   | Universalism-Tolerance     | Acceptance and understanding of those who are different from oneself |
| Justice        | Universalism-Concern       | Commitment to equality, justice, and protection for all people |
| Cosmos         | Universalism-Nature        | Preservation of the natural environment |
| Humility       | Humility                   | Recognizing one’s insignificance in the larger scheme of things |
| Restraint      | Conformity-Interpersonal   | Avoidance of upsetting or harming other people |
| Conformity     | Conformity-Rules           | Compliance with rules, laws, and formal obligations |
| Tradition      | Tradition                  | Maintaining and preserving cultural, family, or religious traditions |
| Others' Safety | Security-Societal          | Safety and stability in the wider society |
| Personal Safety| Security-Personal          | Safety in one’s immediate environment |
| Appearance     | Face | Security and power through maintaining one’s public image and avoiding humiliation |
| Resources      | Power-Resources            | Power through control of material and social resources |
| Dominance      | Power-Dominance            | Power through exercising control over people |
| Achievement    | Achievement                | Personal success through demonstrating competence according to social standards |
| Pleasure       | Hedonism                   | Pleasure and sensuous gratification for oneself |
| Stimulation    | Stimulation                | Excitement, novelty, and challenge in life |
| Free Action    | Self-Direction-Action      | The freedom to determine one’s own actions |
| Free Thought   | Self-Direction-Thought     | The freedom to cultivate one’s own ideas and abilities |

__These values are related to each other.__  The brilliance of this model is that all values are laid out in a [circular continuum](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9131418/figure/fig1-1073191121998760/), so that each blends into the next.  This means that values which are next to each other on the continuum are more highly correlated.  For instance, if you value *conformity* to rules, you are more likely to also value cultural *tradition*.  Values that are opposite each other on the wheel are less related; so that people valuing *conformity* are less likely to value *free action*.

Everything human is here, distilled into the naive simplicity of a diagram: the petty conniving for power, the fear for your children's safety, the striving for freedom, the savoring of wine and chocolate, the rites and celebrations.  It shows the various directions in which we are tugged, and what keeps us awake at night, whether from thrills or fears.  The great loom on which our longings are woven.

__Values shape us as we reach for them.__  *Achievement*, *safety*, *justice*... these are not things that we can attain once and for all, but aspire to.  Their fullness always seems to lie just beyond our reach.  Yet they shape us even now, these visions we reach toward, as the light through the forest canopy shapes a sapling.

__But can we choose what we long for?__  Can we change what we long for and shape ourselves into something new?  If the values arrayed around this circle shade into one another, then it is possible for us to move our affections from one value to another. Perhaps I can choose a different light to lean toward, taking my current jumble of desires and aligning them, re-orienting them.  Do I value being *dependable*, but think that *caring* is a higher calling?^[A quick note on the tools used for the Schwartz Values Scale: Even while filling out the *Portrait Value Questionnaire*, I am aware of at least two ways to read and frame the questions it asks. The tool prompts respondents to "read each description [of an imagined person] and think about how much that person is or is not like you" and then proceeds with a number of statements with the form "It is important to him/her to...".  When filling the questionnaire out, the phrase "it is important to" could mean either that I actively feel and behave as though they are important, or it could imply that I believe it is important for people to do this in general: that the world would be a better place, if we all behaved in such a way. The former reading is helpful for uncovering my shortcomings, while the latter begins to tilt in the direction of virtues.]  Seems like I should re-orient my desires.

## Focus on flourishing

__We need to pare down the list.__  Out of the whole array of values which we could hold, we have to choose some and not others.  After all, many are in tension, or even conflict, with each other (it's hard to value both conformity and free action, for instance).  So if it's possible to choose what we value, how will we make the choice?

__In with the good, out with the bad.__ We can start with a most basic impulse, at the root of everything from our healthcare regimens to our religious rituals: the principle of "in with the good, out with the bad."^[On the subject of religious rituals, Jane Ellen Harrison writes that from the earliest examples, rites have concerned themselves with the "riddance of whatever is conceived to be hostile, and the enhancement of whatever is conceived of as favorable to human life". See: [@harrisonEpilegomenaStudyGreek2017]]  Our goal is to embody what is good and remove what is bad, leaving just good stuff.  I’ll follow Aristotle and call this state "flourishing".

### Flourishing together

Before we begin to call some values generally beneficial (or "healthy") and others generally detrimental (or "unhealthy"), it's important to answer "Beneficial *for whom*?"  After all, I can do many things that benefit me, but harm others or neglect them.

__It has to work for others, too.__ I'm going to move forward with a definition of flourishing that is communal, one which seeks rescue from individualism and "the shipwreck of the singular."^[The phrase is George Oppen's, from his masterful serial poem *Of Being Numerous*, where he defines the stance of modern-day truth-seekers as: "Obsessed, bewildered / By the shipwreck / Of the singular / We have chosen the meaning / Of being numerous." @georgeoppenSelectedPoems2003]

Aspiring to flourish as a community, beyond the narrow vessel of the individual "self", is a principal which should orient human life. There is reason enough to adopt such a principal based on its prevalence across religious and cultural traditions, though one could just as easily make a claim for the evolutionary benefits of such an approach.

__We need each other.__ Once we move beyond "bare survival" (*i.e. zero-sum games*), cooperation allows communities to flourish.  It permits strategies such as improvisation, cultural transmission, and collective tools and rules.^[According to @curryMappingMoralityCompass2019a, "Natural selection can favour genes for cooperation – that is, genes for evolutionarily-stable phenotypic strategies designed to achieve superior equilibria in nonzerosum interactions – and has done throughout the history of life."  The highly social disposition of human beings has "made it possible for humans to attempt to improve upon natural selection’s solutions by inventing evolutionarily-novel solutions – ‘tools and rules’ – for further bolstering cooperation."]

All of which is another way of saying "I am not enough."  I rely on others for my existence, and I want give back; I long to become something which crests above the bounds of the "tiny my-ness"^[To use the term Milosz uses, in the poem of that name. @miloszUnattainableEarth1987] I was given at birth.  It's as though I was granted this self as a ladder, to climb up its rungs and into a wider world: to transcend it.

__Our senses point beyond our separate selves.__  All of the values listed above can, at least indirectly, be faint gestures toward this transcendence. Even the inclination toward physical pleasure (what Schwartz labels *hedonism*) may appear self-centered, but contains an erotic longing beyond myself.^[Aristotle disses this longing for contact as the least refined sensual pleasure, saying that "the licentious enjoy the delight that comes about entirely through *touch*, in food, drink, and the matters said to belong to Aphrodite", but it can equally be seen as our desire, however misled, to feel beyond our skin. @aristotleAristotleNicomacheanEthics2012]  After all, when we really inspect its boundaries, the lines between myself and my surroundings is blurry at best.  My survival, and flourishing, expands beyond my body into community, culture, ecosystem.^[The early cyberneticist Gregory Bateson's mind-and-life-bending essay *Form, Substance, and Difference* traces a compelling argument that "the mental world — the mind — the world of information processing — is not limited by the skin" and then lays out the implications of this insight.  @batesonStepsEcologyMind1999]  With collective flourishing in mind, let's consider whether some types of values or broad goals will tend to bring us nearer.

### Remove the bad

As much as we may chafe at characterizing commonly held values as “less-than” others, in practice we do this all the time.  Imagine a job interview where the prospective candidate announced that their primary values were dominance over others and doing things that brought them pleasure.  Or, imagine a friend calling to tell you “I've met someone and we want to get married.  I think it's a perfect match: he values his own appearance a lot and needs to be continually stimulated in order to stay interested.”  It seems clear enough that not all values lead equally to collective flourishing.

__There are dark behavior patterns.__ In psychological research, certain behavioral patterns have been identified as running contrary to this goal.  These patterns have been given a suggestive name: the Dark Triad (or Tetrad).^[The "Dark Triad" refers to the malevolent and anti-social personality traits of *Machiavellianism* (treating other people as a means to achieve one's own ends), *narcissism* (obsession with oneself and belief that you are superior to others), and *psychopathy* (lack of empathy and willingness to exploit others).  More recent studies have expanded this to a "Dark Tetrad", adding *sadism* (deriving pleasure from the pain or discomfort of others).]

The use of the metaphor "dark" is worth dwelling on for a moment, since it points back to a old stock of images.  The association of "darkness" with evil seems entwined with our bodies' biological sense, which is to say, with our *umwelt*.  The poem "One More Day"^[@miloszUnattainableEarth1987] puts it emphatically: 

> should we discredit the idea for its modest origins?  
> Or should we say plainly that good is on the side of the living  
> And evil on the side of a doom that lurks to devour us?  
> Yes, good is an ally of being and the mirror of evil is nothing,  
> Good is brightness, evil darkness, good high, evil low,  
> According to the nature of our bodies, of our language.  

The action associated with "darkness" is a retreat from others and the world into a self-contained loop (i.e. a 'vicious cycle').^[When historical cultures have chosen to depict untrustworthy or diabolical characters, they often depicted them as crooked or hunched over. While those with congenital issues have suffered unjustly from these depictions, the images provide a physical form for a pattern of behavior.]  When Augustine sought to sum up the peculiar infirmity of the human species, he said that we were "curved in on ourselves": *homo incurvatus in se*.   Current research into dark personality patterns seems to agree.

__Are certain values or traits "dark"?__  




### Keep the good
